In [1]:
import torch
import numpy as np

In [3]:
data=[[1,2,3],[2,3,4],[3,4,5]]
x=torch.tensor(data)
x

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [4]:
np_array=np.array(data)
x=torch.from_numpy(np_array)

In [6]:
x=torch.ones_like(x)
print(f'tensor:\n {x}\n')

x_rand=torch.rand_like(x,dtype=torch.float)
print(f'sdas:\n{x_rand}\n')

tensor:
 tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

sdas:
tensor([[0.6670, 0.1325, 0.4042],
        [0.6309, 0.5230, 0.1644],
        [0.5935, 0.4169, 0.4714]])



In [12]:
shape=(2,3,)
ran=torch.rand(shape)
one=torch.ones(shape)
zero=torch.zeros(shape)
print(f'asd:\n{ran}\n')
print(f'one:\n{one}\n')
print(f'asd:\n{zero}\n')

asd:
tensor([[0.4284, 0.2897, 0.1644],
        [0.4671, 0.4765, 0.5624]])

one:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

asd:
tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [14]:
tensor=torch.rand(3,4)
print(f'shape:{tensor.shape}')
print(f'tensor:{tensor.dtype}')
print(f'device:{tensor.device}')

shape:torch.Size([3, 4])
tensor:torch.float32
device:cpu


In [16]:
if torch.cuda.is_available():
    tensor=tensor.to('cuda')

In [20]:
tensor=torch.rand(100,1500)
print(f'raw:{tensor[0]}')
print(f'Fcolumn: {tensor[:0]}')
print(f'Lcolumn: {tensor[...,-1]}')
tensor[:-1]=0
print(tensor)

raw:tensor([0.8940, 0.4367, 0.7004,  ..., 0.4287, 0.6499, 0.1944])
Fcolumn: tensor([], size=(0, 1500))
Lcolumn: tensor([0.1944, 0.5270, 0.9064, 0.9972, 0.4871, 0.3363, 0.8108, 0.8879, 0.0857,
        0.1737, 0.6100, 0.8751, 0.2878, 0.4145, 0.4040, 0.8466, 0.5478, 0.3403,
        0.6830, 0.4890, 0.4016, 0.2677, 0.9797, 0.1519, 0.3741, 0.9012, 0.1519,
        0.4155, 0.1359, 0.6321, 0.5913, 0.1935, 0.6942, 0.6883, 0.5056, 0.3810,
        0.4983, 0.7797, 0.1937, 0.3039, 0.5400, 0.4426, 0.6291, 0.2794, 0.5680,
        0.3770, 0.8056, 0.7539, 0.8615, 0.3364, 0.6977, 0.0556, 0.1061, 0.9603,
        0.2981, 0.0505, 0.3444, 0.5737, 0.4801, 0.5643, 0.3730, 0.9660, 0.9460,
        0.0089, 0.5938, 0.4665, 0.3966, 0.7588, 0.2198, 0.8402, 0.6150, 0.7766,
        0.9865, 0.0224, 0.7908, 0.7501, 0.5524, 0.3406, 0.9136, 0.6183, 0.3928,
        0.7558, 0.5759, 0.9723, 0.8122, 0.4343, 0.3132, 0.3486, 0.0994, 0.1823,
        0.2464, 0.5794, 0.5488, 0.6991, 0.7210, 0.2015, 0.2275, 0.7841, 0.7112,
        

In [24]:
t1=torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.3093, 0.5766, 0.7608,  ..., 0.9124, 0.3070, 0.8958]])


In [67]:
y1=tensor @ tensor.T
y2=tensor.matmul(tensor.T)
y3=torch.rand_like(y1)#input과 동일한 shape//randn() 인풋과 동일한 형태의 가우스분포로 텐서 난수생성
torch.matmul(tensor, tensor.T, out=y3)


tensor([[  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
        ...,
        [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000, 510.0573]])

In [73]:
z1=tensor*tensor
z2=tensor.mul(tensor)
z3=torch.rand_like(tensor)
torch.mul(tensor,tensor, out=z3)

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0957, 0.3325, 0.5788,  ..., 0.8325, 0.0943, 0.8025]])

In [74]:
agg=tensor.sum()
agg_item=agg.item()
print(agg_item, type(agg_item))

767.6175537109375 <class 'float'>


In [75]:
print(f"tensor\n")
tensor.add(5)
print(tensor)

tensor

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.3093, 0.5766, 0.7608,  ..., 0.9124, 0.3070, 0.8958]])


In [86]:
t=torch.ones(5)
print(t)
n=t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [87]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [88]:
n=np.ones(5)
t=torch.from_numpy(n)
np.add(n,1,out=n)
print(f'{t}')
print(f'{n}')

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
