In [2]:
import torch
form torch.utils

'2.1.1+cu121'

In [7]:
x=torch.zeros(4,5,dtype=torch.long)
x

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [10]:
x=torch.tensor([3,2.4])
x

tensor([3.0000, 2.4000])

In [13]:
x=x.new_ones(4,5,dtype=torch.double)
x

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [20]:
x=torch.rand_like(x,dtype=torch.int)
x.size()

RuntimeError: "check_uniform_bounds" not implemented for 'Int'

In [24]:
x=torch.cuda.IntTensor([1,2,3])
x
x.size()

torch.Size([3])

In [27]:
x.long()

tensor([1, 2, 3], device='cuda:0')

In [34]:
x=torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.9099])
0.9099021553993225
torch.float32


In [35]:
device=torch.device('cuda'if torch.cuda.is_available() else'CPU')
print(f'{device} mode')
y=torch.ones_like(x,device=device)
print(x)
print(y)
z=x+y
print(z)
print(z.to('cpu',torch.double))

cuda mode
tensor([0.9099])
tensor([1.], device='cuda:0')


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [36]:
import math

a=torch.rand(1,2)*2-1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a,-0.5,0.5))

tensor([[-0.8685, -0.8809]])
tensor([[0.8685, 0.8809]])
tensor([[-0., -0.]])
tensor([[-1., -1.]])
tensor([[-0.5000, -0.5000]])


In [42]:
x=torch.randn(4,5)
print(x)
y=x.view(20)
print(y)
z=x.view(5,-1)  #->-1은 컴에게 알라서 하라는 의미
print(z)

tensor([[ 3.4599e-01,  7.2298e-01,  2.7147e-01,  8.9141e-01, -1.0599e-01],
        [ 3.8128e-01, -8.6248e-01, -8.4854e-01,  7.6116e-01,  2.0464e+00],
        [ 5.3688e-01,  1.5905e-03, -1.2695e+00, -2.7470e+00, -7.1287e-01],
        [ 1.1109e+00, -3.9127e-01,  1.8254e+00,  6.6396e-01, -9.5463e-01]])
tensor([ 3.4599e-01,  7.2298e-01,  2.7147e-01,  8.9141e-01, -1.0599e-01,
         3.8128e-01, -8.6248e-01, -8.4854e-01,  7.6116e-01,  2.0464e+00,
         5.3688e-01,  1.5905e-03, -1.2695e+00, -2.7470e+00, -7.1287e-01,
         1.1109e+00, -3.9127e-01,  1.8254e+00,  6.6396e-01, -9.5463e-01])
tensor([[ 3.4599e-01,  7.2298e-01,  2.7147e-01,  8.9141e-01],
        [-1.0599e-01,  3.8128e-01, -8.6248e-01, -8.4854e-01],
        [ 7.6116e-01,  2.0464e+00,  5.3688e-01,  1.5905e-03],
        [-1.2695e+00, -2.7470e+00, -7.1287e-01,  1.1109e+00],
        [-3.9127e-01,  1.8254e+00,  6.6396e-01, -9.5463e-01]])


In [44]:
x=torch.randn(1)
print(x)
print(x.item()) #->요소값을 자세히 표시하는 놈

tensor([-0.6418])
-0.641831636428833


In [54]:
x=torch.randn(1,3,3)
print(x)
t=x.squeeze()
print(t.shape)
print(t)
t=x.unsqueeze(dim=-1)
print(t.shape)
print(t)

tensor([[[-0.0096,  1.1404,  1.0293],
         [ 0.3941, -0.9326,  0.6857],
         [ 1.0929,  0.1834, -0.2519]]])
torch.Size([3, 3])
tensor([[-0.0096,  1.1404,  1.0293],
        [ 0.3941, -0.9326,  0.6857],
        [ 1.0929,  0.1834, -0.2519]])
torch.Size([1, 3, 3, 1])
tensor([[[[-0.0096],
          [ 1.1404],
          [ 1.0293]],

         [[ 0.3941],
          [-0.9326],
          [ 0.6857]],

         [[ 1.0929],
          [ 0.1834],
          [-0.2519]]]])


In [56]:
#stack->tensor간 결합.
x=torch.FloatTensor([1,4])
print(x)
y=torch.FloatTensor([2,4])
print(y)
z=torch.FloatTensor([3,4])
print(z)
torch.stack([x,y,z])

tensor([1., 4.])
tensor([2., 4.])
tensor([3., 4.])


tensor([[1., 4.],
        [2., 4.],
        [3., 4.]])

In [59]:
#cat ->결합(컨케터네이트) dim=x :몇번째를 기준으로 할것인가
a=torch.randn(1,2,3)
print(a)
b=torch.randn(1,2,3)
print(a)
c=torch.cat((a,b),dim=1)
print(a)

tensor([[[-0.6660, -0.2454,  0.8864],
         [ 0.5101,  0.4208, -1.1844]]])
tensor([[[-0.6660, -0.2454,  0.8864],
         [ 0.5101,  0.4208, -1.1844]]])
tensor([[[-0.6660, -0.2454,  0.8864],
         [ 0.5101,  0.4208, -1.1844]]])


In [75]:
tensor=torch.randn(3,6)
print(tensor)

#t1,t2,t3=torch.chunk(tensor,3,dim=1)  #chunk->합쳐진놈을 몇 개로 쪼개는것 기준=dim=x 비슷한 놈으로 split이 존재(텐서 크기가 몇 인가로 나눔)
t1,t2,t3=torch.split(tensor,2,dim=1)  #chunk->합쳐진놈을 몇 개로 쪼개는것 기준=dim=x 비슷한 놈으로 split이 존재(텐서 크기가 몇 인가로 나눔)

print(t1)
print(t2)
print(t3)

tensor([[-1.6426,  0.1986,  0.2050,  0.9172, -0.6939,  0.4250],
        [ 0.3290, -1.6789, -0.3216, -1.2166,  0.3894,  0.4547],
        [ 0.2738, -1.3734, -1.4025, -0.0725,  0.0253,  0.7882]])
tensor([[-1.6426,  0.1986],
        [ 0.3290, -1.6789],
        [ 0.2738, -1.3734]])
tensor([[ 0.2050,  0.9172],
        [-0.3216, -1.2166],
        [-1.4025, -0.0725]])
tensor([[-0.6939,  0.4250],
        [ 0.3894,  0.4547],
        [ 0.0253,  0.7882]])


In [78]:
#메모리가 공유됨(CPU한정)

a=torch.ones(7)
b=a.numpy()
print(a)
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2.]


In [84]:
#오토그레디어트
a=torch.randn(3,3)
a=a*3
print(a)
print(a.requires_grad)

tensor([[-1.8034,  0.3982, -3.0322],
        [ 0.1118, -4.9755,  2.7026],
        [-2.0886,  5.3565,  0.1524]])
False


In [113]:
a.requires_grad_(True)
print(z.requires_grad)

b=(a*a).sum()
print(b)
print(b.grad_fn)

True
tensor(77.7554, grad_fn=<SumBackward0>)


In [114]:
#gradient
x=torch.ones(3,3, requires_grad=True)
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [115]:
y=x+5
print(y)
z=y*y
out=z.mean()
print(z,out)

print(out)
out.backward()
print(x.grad)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)
tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)
tensor(36., grad_fn=<MeanBackward0>)
tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [116]:
x=torch.rand(3,requires_grad=True)
y=x*2
while y.data.norm()<10000:
    y=y*2
    
print(y)
v=torch.tensor([0.1,1.0,0.001],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([4078.4043, 6410.8340, 7465.1289], grad_fn=<MulBackward0>)
tensor([ 1638.4000, 16384.0000,    16.3840])


In [119]:
a, b=2, 5
def add(num):
    global a
    a += num
    return a

def adds(num):
    global b
    b += num
    return b

print(add(2))
print(adds(4))


4
9


In [137]:
class test:
    def __init__(self):
        self.result=0
    def add(self,num):
        self.result += num
        return self.result
    def zmfhtm(self,num):
        self.result **= num
        return self.result
cal1=test()
cal2=test()

print(cal1.add(4))
print(cal1.add(2))


4
6


In [140]:
x_train=torch.FloatTensor([[3],[4],[5]])
y_train=torch.FloatTensor([[3],[5],[6]])
print(f'{x_train},{y_train}')

tensor([[3.],
        [4.],
        [5.]]),tensor([[3.],
        [5.],
        [6.]])


In [263]:
import torch
from torch import nn
import torch.nn.functional as fn
import torch.optim as opt

In [264]:
torch.manual_seed(1)

In [265]:
w=torch.zeros(1,requires_grad=True)
w

tensor([0.], requires_grad=True)

In [266]:
b = torch.zeros(1, requires_grad=True)
print(b)


tensor([0.], requires_grad=True)


In [267]:
hyper=x_train*w+b
print(hyper)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [268]:
cost=torch.mean((hyper-y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [269]:
opt=opt.SGD([w,b],lr=0.01)
#optimizer = opt.SGD([w, b], lr=0.01)


In [289]:
opt.zero_grad()

cost.backward()

opt.step()

AttributeError: module 'torch.optim' has no attribute 'zero_grad'

In [293]:
import torch
from torch import nn
import torch.nn.functional as fn
import torch.optim as opt

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = opt.SGD([W, b], lr=0.01)

nb_epochs = 2000 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))



Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

In [298]:
import torch
w=torch.tensor(2.0, requires_grad=True)
nb_epoch=20
for epochs in range(nb_epoch+1):
    z=2*w
    z.backward()
    print('{}'.format(w.grad))

2.0
4.0
6.0
8.0
10.0
12.0
14.0
16.0
18.0
20.0
22.0
24.0
26.0
28.0
30.0
32.0
34.0
36.0
38.0
40.0
42.0


In [323]:
import torch
torch.manual_seed(3)
for i in range(1,3):
    print(torch.rand(1))

tensor([0.0043])
tensor([0.1056])


In [324]:
torch.manual_seed(3)
print(torch.rand(3))

tensor([0.0043, 0.1056, 0.2858])


In [325]:
y=w**2
z=2*y+5
z.backward()
print('{}'.format(w.grad))

82.0


In [345]:
import torch
from torch.utils.data import DataLoader
import os
import torch.nn as nn
import torch.nn.functional as fg
import torch.optim as opt

In [346]:
torch.manual_seed(1)

x1_train=torch.FloatTensor([[23],[34],[45],[56]])
x2_train=torch.FloatTensor([[88],[98],[45],[23]])
x3_train=torch.FloatTensor([[45],[44],[47],[79]])
y_train=torch.FloatTensor([[153],[159],[756],[256]])

In [347]:
w1=torch.zeros(1,requires_grad=True)
w2=torch.zeros(1,requires_grad=True)
w3=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)

In [348]:
opt=opt.SGD([w1,w2,w3,b],lr=1e-5)
nb_epoch=1000
for eporchs in range(nb_epoch+1):
    hyper=x1_train*w1+x2_train*w2+x3_train*w3+b
    cost=torch.mean((hyper-y_train)**2)
    opt.zero_grad()
    cost.backward()
    opt.step()
    
    if epochs % 100==0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))


In [352]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])
print(x_train.shape)
print(y_train.shape)
# 가중치와 편향 선언
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
print(w)
print(b)

torch.Size([5, 3])
torch.Size([5, 1])
tensor(2., requires_grad=True)
tensor([0.], requires_grad=True)


In [380]:
import torch
import torch.nn as nn
import torch.nn.functional as fn
import torch.optim as opt
torch.manual_seed(1)
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

model=nn.Linear(1,1)
print(list(model.parameters()))

opt=opt.SGD(model.parameters(),lr=0.01)
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = fn.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    opt.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    opt.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print(f'Epoch {epoch}/{nb_epochs} Cost: {cost.item()}')

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
Epoch 0/2000 Cost: 13.103541374206543
Epoch 100/2000 Cost: 0.00279058120213449
Epoch 200/2000 Cost: 0.00172441138420254
Epoch 300/2000 Cost: 0.0010655784280970693
Epoch 400/2000 Cost: 0.0006584661896340549
Epoch 500/2000 Cost: 0.0004068926500622183
Epoch 600/2000 Cost: 0.0002514346851967275
Epoch 700/2000 Cost: 0.00015537298168055713
Epoch 800/2000 Cost: 9.601024794392288e-05
Epoch 900/2000 Cost: 5.9327696362743154e-05
Epoch 1000/2000 Cost: 3.66610438504722e-05
Epoch 1100/2000 Cost: 2.2655576685792767e-05
Epoch 1200/2000 Cost: 1.3999051589053124e-05
Epoch 1300/2000 Cost: 8.65114816406276e-06
Epoch 1400/2000 Cost: 5.346103989722906e-06
Epoch 1500/2000 Cost: 3.3032331430149497e-06
Epoch 1600/2000 Cost: 2.04174443751981e-06
Epoch 1700/2000 Cost: 1.2618406799447257e-06
Epoch 1800/2000 Cost: 7.801028800713539e-07
Epoch 1900/2000 Cost: 4.823282324650791e-07
Epoch 2000/2

In [384]:
new_val=torch.FloatTensor([[4.]])
pred_y=model(new_val)
print(pred_y)
print(list(model.parameters()))

tensor([[7.9989]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [398]:
import torch
import torch.nn as nn
import torch.nn.functional as fn

torch.manual_seed(1)

# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])
model=nn.Linear(3,1)
print(list(model.parameters()))

opt=torch.optim.SGD(model.parameters(),lr=1e-4)

nb_epochs=2000
for epoch in range(nb_epochs+1):
    prediction=model(x_train)
    cost=fn.mse_loss(prediction, y_train)
    opt.zero_grad()
    cost.backward()
    opt.step()
    
    if epoch %100==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]
Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: nan
Epoch  200/2000 Cost: nan
Epoch  300/2000 Cost: nan
Epoch  400/2000 Cost: nan
Epoch  500/2000 Cost: nan
Epoch  600/2000 Cost: nan
Epoch  700/2000 Cost: nan
Epoch  800/2000 Cost: nan
Epoch  900/2000 Cost: nan
Epoch 1000/2000 Cost: nan
Epoch 1100/2000 Cost: nan
Epoch 1200/2000 Cost: nan
Epoch 1300/2000 Cost: nan
Epoch 1400/2000 Cost: nan
Epoch 1500/2000 Cost: nan
Epoch 1600/2000 Cost: nan
Epoch 1700/2000 Cost: nan
Epoch 1800/2000 Cost: nan
Epoch 1900/2000 Cost: nan
Epoch 2000/2000 Cost: nan


In [401]:
import torch
import torch.nn as nn

'''클래스(class) 형태의 모델은 nn.Module 을 상속받습니다. 
그리고 __init__()에서 모델의 구조와 동작을 정의하는 생성자를 정의합니다.
이는 파이썬에서 객체가 갖는 속성값을 초기화하는 역할로,
객체가 생성될 때 자동으로 호출됩니다. 
super() 함수를 부르면 여기서 만든 클래스는 nn.Module 클래스의 속성들을 가지고 초기화 됩니다. 
foward() 함수는 모델이 학습데이터를 입력받아서 forward 연산을 진행시키는 함수입니다.
이 forward() 함수는 model 객체를 데이터와 함께 호출하면 자동으로 실행이됩니다.
예를 들어 model이란 이름의 객체를 생성 후, model(입력 데이터)와 같은 형식으로 
객체를 호출하면 자동으로 forward 연산이 수행됩니다.'''
#model=nn.Linear(1,1) ->이게 저거
class LRM(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(1,1)
        
    def forward(self, x):
        return self.linear(x)
    
model=LRM()

#model=nn.Linear(3,1)
class MLRM(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)
        
    def forward(self,x):
        return self.linear(x)
    
model=MLRM()

In [1]:
import torch
import torch.nn as nn
import torch.functional as F
torch.manual_seed(3)

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

class LRM(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)
model=LRM()

opt=torch.optim.SGD(model.parameters(),lr=0.01)

nb_epochs=20000
for i in range(nb_epochs+1):
    #prediction=model(x_train)
    prediction = model(x_train)

    #cost=fn.mse_loss(prediction,y_train)
    cost=F.mse_loss(prediction,y_train)
    
    opt.zero_grad()
    cost.backward()
    opt.step()
    if i %100==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          i, nb_epochs, cost.item()
        ))        

AttributeError: module 'torch.functional' has no attribute 'mse_loss'

In [ ]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs=2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    opt.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    opt.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))
